services:
  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    env_file:
      - "compose/aws.env"
    profiles:
      - use-localstack
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/data

  service:
    build:
      context: .
      target: development
    ports:
      - 8086:8086
    links:
      - "mongodb:mongodb"
    depends_on:
      mongodb:
        condition: service_started
    profiles:
      - service
    env_file:
      - "compose/aws.env"
      - "compose/secrets.env"
    environment:
      PORT: ${PORT:-8086}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
    volumes:
      - ./app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ./pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
