services:
  ai-defra-search-agent:
    build:
      target: development
    image: ai-defra-search-agent-development
    container_name: ai-defra-search-agent-test
    entrypoint: uv run task test
    env_file:
      - path: .env
        required: false
    environment:
      PORT: ${PORT:-8086}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
    volumes:
      - ./app/:/home/nonroot/app
      - ./tests/:/home/nonroot/tests
      - ./coverage:/home/nonroot/coverage:rw
      - ./pytest.ini:/home/nonroot/pytest.ini:ro
