services:
  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - "27018:27017"
    volumes:
      - mongodb-test-data:/data

  ai-defra-search-agent:
    build:
      target: development
    image: ai-defra-search-agent-development
    container_name: ai-defra-search-agent-test
    entrypoint: uv run task test
    depends_on:
      mongodb:
        condition: service_started
    env_file:
      - path: .env
        required: false
    environment:
      AWS_REGION: ${AWS_REGION:-eu-central-1}
      PORT: ${PORT:-8086}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      LOCALSTACK_URL: ${LOCALSTACK_URL:-http://localstack:4566}
      AWS_BEDROCK_DEFAULT_GENERATION_MODEL: 'genai-3-turbo'
    volumes:
      - ./app/:/home/nonroot/app
      - ./tests/:/home/nonroot/tests
      - ./coverage:/home/nonroot/coverage:rw
      - ./pytest.ini:/home/nonroot/pytest.ini:ro
    networks:
      - cdp-tenant

volumes:
  mongodb-test-data: